### PR TITLE
Add Skewed Infinite Scroll Component

### PR DESCRIPTION
**Pull request by Tahermaxse**
- Added the Skewed Infinite Scroll component under the Components section.
- Included demo usage and updated relevant code.
- Added CSS styles for the component.
- Conducted code review and made necessary adjustments.

### CODE REVIEW

**Comment by Tahermaxse** [comment]
Done

**Comment by Tahermaxse** [comment]
Done Skewed Infinite Scroll Component added without conflict 👍

**Comment by Tahermaxse** [comment]
Done Skewed Infinite Scroll Component added without conflict 👍

**Comment by DavidHDev** [comment]
Hi @Tahermaxse , I didn't have a plan to accept any components other than the ones I planned to add (each of them are already planned out with how they're going to look, where the inspiration is from), but since you already did the work I don't want to waste your time. 

Few things:
- Find a better name for the component, prefferably with only two words, so it fits better in the sidebar
- Add a video for me to see what it looks like
- If possible, add the tailwind version of it (you'd have to test it on an external tailwind project to make sure it works, because we don't use tailwind here)

After this, I will be doing the code review and we'll merge it after

**Comment by Tahermaxse** [comment]
Hey David,

Thanks for your feedback! I completely understand the need to stick to the
planned components. I’ll take care of the following:


   - I’ll come up with a better name for the component, keeping it to two
   words for better sidebar fit.
   - I’ll record and share a video to show how the component looks in
   action.
   - I’ll also create and test a Tailwind version on an external project to
   make sure it works.
   - I’ll have everything ready before the code review. Let me know if you
   have any other inputs.

Best,
Taher

**Pull request closed without merging**
